In [1]:
#Buatlah sebuah fungsi untuk membuat matrix berdasarkan input dari user
import numpy as np

def create_matrix(baris,kolom):
    matrix = [[0 for j in range (kolom)]for i in range (baris)]
    for i in range (baris):
        for j in range (kolom):
            matrix[i][j] =int(input(f"Masukkan angka untuk [{i+1}][{j+1}] : "))

    ViewMatrix = np.array(matrix)
    return ViewMatrix


print(create_matrix(baris = int(input('Masukkan Jumlah Baris:\t')), kolom = int(input('Masukkan Jumlah Kolom:\t'))))

[[1 2]
 [3 1]]


In [8]:
#Buatlah sebuah fungsi untuk mencari determinan matrix berdasarkan input matrix dari user

import numpy as np

def determinan():
    baris = int(input('Masukkan Jumlah Baris Matrix : '))
    kolom = int(input('Masukkan Jumlah Kolom Matrix : '))
    if baris == 2 and kolom == 2:
        det = []
        matrix = [[0 for j in range (kolom)]for i in range (baris)]
        for i in range(baris):
            for j in range(kolom):
                matrix[i][j] =int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
        view_matrix = np.array(matrix)
        print(f'Matrix: \n{view_matrix}')
        hitung_determinan = (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])
        det.append(hitung_determinan)
        int_det = det[0]
    elif baris == 3 and kolom == 3:
        det = []
        matrix = [[0 for j in range (kolom)]for i in range (baris)]
        for i in range(baris):
            for j in range(kolom):
                matrix[i][j] =int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
        view_matrix = np.array(matrix)
        print(f'Matrix: \n{view_matrix}')
        hitung_determinan = (matrix[0][0] * matrix[1][1] * matrix[2][2]) + (matrix[0][1] * matrix[1][2] * matrix[2][0]) + (matrix[0][2] * matrix[1][0] * matrix[2][1]) - (matrix[0][2] * matrix[1][1] * matrix[2][0]) - (matrix[0][1] * matrix[1][0] * matrix[2][2]) - (matrix[0][0] * matrix[1][2] * matrix[2][1])
        det.append(hitung_determinan)
        int_det = det[0]
    else:
        print('Maaf program ini hanya bisa untuk matrix 2x2 dan matrix 3x3')

    return int_det
print('Determinan dari matrix tersebut adalah', determinan())

Matrix: 
[[3 4 5]
 [4 2 3]
 [2 3 5]]
Determinan dari matrix tersebut adalah -13


In [5]:
#Buatlah fungsi untuk mengakalikan dua buah matrix berdasarkan input user menggunakan nested loop

def create_matrix1(baris1, kolom1):
    global matrix1
    matrix1 = [[0 for j in range(kolom1)]for i in range(baris1)]
    for i in range(baris1):
        for j in range(kolom1):
            matrix1[i][j] = int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
    return matrix1
 
baris1 = int(input('Masukkan Jumlah Baris Matrix 1:\t'))
kolom1 = int(input('Masukkan Jumlah Kolom Matrix 1:\t'))
create_matrix1(baris1, kolom1)

def create_matrix2(baris2, kolom2):
    global matrix2
    matrix2 = [[0 for j in range(kolom2)]for i in range(baris2)]
    for i in range(baris2):
        for j in range(kolom2):
            matrix2[i][j] = int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
    return matrix2


baris2 = int(input('Masukkan Jumlah Baris Matrix 2:\t'))
kolom2 = int(input('Masukkan Jumlah Kolom Matrix 2:\t'))
create_matrix2(baris2, kolom2)

def multiply_matrix(matrix1, matrix2):
    m = len(matrix1)
    n = len(matrix2[0])
    p = len(matrix2)
    
    result = [[0 for j in range(n)] for i in range(m)]
    for i in range(m):
        for j in range(n):
            for k in range(p):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    
    for r in result:
        print(r)

print('matrix 1 =',matrix1)
print('matrix 2 =',matrix2)
multiply_matrix(matrix1, matrix2)

matrix 1 = [[1, 2, 3], [2, 3, 2], [3, 3, 4]]
matrix 2 = [[3, 1], [4, 6]]
[11, 13]
[18, 20]
[21, 21]
